In [31]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [1]:
import numpy as np

In [33]:
from model.gradients import neg_logloss_softmax_grad

In [34]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=1)[:,None]



In [35]:
a = np.random.randint(0,4,(10,3))

In [36]:
b=softmax(a)
b

array([[0.24472847, 0.66524096, 0.09003057],
       [0.10650698, 0.10650698, 0.78698604],
       [0.09003057, 0.24472847, 0.66524096],
       [0.24472847, 0.09003057, 0.66524096],
       [0.48785555, 0.0242889 , 0.48785555],
       [0.24472847, 0.09003057, 0.66524096],
       [0.4223188 , 0.4223188 , 0.1553624 ],
       [0.09003057, 0.24472847, 0.66524096],
       [0.33333333, 0.33333333, 0.33333333],
       [0.1141952 , 0.84379473, 0.04201007]])

In [38]:
true_b=np.random.randint(0,3,(10,))
true_b

array([0, 0, 0, 2, 1, 0, 2, 0, 0, 0])

In [41]:
neg_logloss_softmax_grad(true_b,b)

array([[0.75527153, 0.        , 0.        ],
       [0.89349302, 0.        , 0.        ],
       [0.90996943, 0.        , 0.        ],
       [0.        , 0.        , 0.33475904],
       [0.        , 0.9757111 , 0.        ],
       [0.75527153, 0.        , 0.        ],
       [0.        , 0.        , 0.8446376 ],
       [0.90996943, 0.        , 0.        ],
       [0.66666667, 0.        , 0.        ],
       [0.8858048 , 0.        , 0.        ]])