In [1]:
import numpy as np

In [23]:
a = np.random.randint(0,4,(10,3))
a.shape


(10, 3)

In [26]:
a

array([[0, 3, 1],
       [2, 2, 2],
       [1, 0, 0],
       [0, 2, 2],
       [2, 2, 1],
       [3, 2, 2],
       [1, 0, 2],
       [1, 2, 3],
       [1, 1, 2],
       [0, 0, 1]])

In [45]:
def softmax(x):
    return np.exp(x) / np.sum(np.exp(x), axis=1)[:,None]

def stable_softmax(x):
    e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e_x / np.sum(e_x, axis=-1, keepdims=True)



In [46]:
b=softmax(a)
b

array([[0.04201007, 0.84379473, 0.1141952 ],
       [0.33333333, 0.33333333, 0.33333333],
       [0.57611688, 0.21194156, 0.21194156],
       [0.06337894, 0.46831053, 0.46831053],
       [0.4223188 , 0.4223188 , 0.1553624 ],
       [0.57611688, 0.21194156, 0.21194156],
       [0.24472847, 0.09003057, 0.66524096],
       [0.09003057, 0.24472847, 0.66524096],
       [0.21194156, 0.21194156, 0.57611688],
       [0.21194156, 0.21194156, 0.57611688]])

In [49]:
bb = stable_softmax(a)
bb * (1-bb)

array([[0.04024522, 0.13180518, 0.10115466],
       [0.22222222, 0.22222222, 0.22222222],
       [0.24420622, 0.16702233, 0.16702233],
       [0.05936205, 0.24899578, 0.24899578],
       [0.24396563, 0.24396563, 0.13122493],
       [0.24420622, 0.16702233, 0.16702233],
       [0.18483645, 0.08192507, 0.22269543],
       [0.08192507, 0.18483645, 0.22269543],
       [0.16702233, 0.16702233, 0.24420622],
       [0.16702233, 0.16702233, 0.24420622]])

In [29]:
true_b=np.random.randint(0,3,(10,))
true_b

array([1, 2, 0, 0, 2, 2, 1, 0, 1, 1])

In [32]:
np.max(true_b)

2

In [34]:
def one_hot(x):
    n_values = np.max(x)+1
    return np.eye(n_values)[x]

In [44]:
np.mean(np.log(np.sum(one_hot(true_b) * b,axis=1)))

-1.5910067572579125

In [41]:
from sklearn.metrics import log_loss

In [42]:
log_loss(true_b,b)

1.5910067572579125

In [11]:
np.sum(a,axis=1)

array([2, 4, 6, 2, 0, 3, 1, 4, 5, 2])

In [11]:
np.ones((10,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])